apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-second-app-name
  labels:
    app: second-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: second-app
  template:
    metadata:
      labels:
        app: second-app
    spec:
      containers:
        - name: second-app
          image: ~/usr/src/app
          ports:
            - containerPort: 2000
